version: '3.8'

services:
  ci:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm test
    volumes:
      - .:/app
    working_dir: /app

  deploy:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "pnpm install --prod --ignore-scripts && pnpm prisma generate && pnpm run start"
    volumes:
      - .:/app
    working_dir: /app
