version: '3.8'

services:
  bot:
    build: .
    container_name: discord-bot
    restart: always
    networks:
      discord-bot-net:
        ipv4_address: 10.200.0.2

networks:
  discord-bot-net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/16
